// Generated by Wrangler on Sun Apr 28 2024 22:57:06 GMT+1200 (New Zealand Standard Time)
// by running `wrangler types`
type QueueMessages =
| {type: 'subscribe', email: string, code: string}
| {type: 'dailytopic', email: string, code: string, topic: string}


interface Env {
	SMTP_FROM: string;
	AWS_REGION: string;
	AWS_ACCESS_KEY_ID: string;
	AWS_SECRET_ACCESS_KEY: string;
	EMAIL_ENROLLMENT_QUEUE: Queue;
}
