// Generated by Wrangler on Sat May 04 2024 22:55:11 GMT+1200 (New Zealand Standard Time)
// by running `wrangler types`

interface Env {
	AWS_REGION: "ap-southeast-2";
	SMTP_FROM: string;
	AWS_ACCESS_KEY_ID: string;
	AWS_SECRET_ACCESS_KEY: string;
	EMAIL_QUEUE: Queue;
}
