// Generated by Wrangler on Tue May 07 2024 21:10:31 GMT+1200 (New Zealand Standard Time)
// by running `wrangler types`

interface Env {
	AWS_REGION: "ap-southeast-2";
	SMTP_FROM: string;
	AWS_ACCESS_KEY_ID: string;
	AWS_SECRET_ACCESS_KEY: string;
	DB: D1Database;
	EMAIL_QUEUE: Queue;
}
