#:schema node_modules/wrangler/config-schema.json
name = "speechtopics-email"
main = "src/index.ts"
compatibility_date = "2024-04-23"
node_compat = true

logpush = true

# Automatically place your workloads in an optimal location to minimize latency.
# If you are running back-end logic in a Worker, running it closer to your back-end infrastructure
# rather than the end user may result in better performance.
# Docs: https://developers.cloudflare.com/workers/configuration/smart-placement/#smart-placement
# [placement]
# mode = "smart"

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Docs:
# - https://developers.cloudflare.com/workers/wrangler/configuration/#environment-variables
# Note: Use secrets to store sensitive data.
# - https://developers.cloudflare.com/workers/configuration/secrets/
# [vars]
# MY_VARIABLE = "production_value"

# Bind a Queue producer. Use this binding to schedule an arbitrary task that may be processed later by a Queue consumer.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#queues
[[queues.producers]]
binding = "EMAIL_QUEUE"
queue = "speechtopics-email"

# Bind a Queue consumer. Queue Consumers can retrieve tasks scheduled by Producers to act on them.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#queues
[[queues.consumers]]
queue = "speechtopics-email"
# Optional: Configure batching and retries: https://developers.cloudflare.com/queues/learning/batching-retries/
# max_batch_size = 10
# max_batch_timeout = 30
# max_retries = 10
# dead_letter_queue = "my-queue-dlq"

[[d1_databases]]
binding = "DB"
database_name = "speechtopics"
database_id = "2ecc3066-ce72-494d-b828-6b668cf796ec"

[vars]
AWS_REGION = "ap-southeast-2"
SMTP_FROM = "Daily speech topic <daily@speechtopics.markhamilton.dev>"

[triggers]
crons = [ "0 18 * * *"]
